film_production:
  target: local
  outputs:
    local:
      type: duckdb
      path: ':memory:'
      database: ducklake
      threads: 1
      schema: dbo
      extensions:
        - parquet
        - sqlite
        - ducklake
        - name: delta_export
          repo: community
      attach:
        - path: "ducklake:sqlite:./data/metadata.db"
          alias: ducklake
          options:
            data_path: "./data/Tables"
            data_inlining_row_limit: 0
    fabric:
      type: duckdb
      path: ':memory:'
      database: ducklake
      threads: 1
      schema: dbo
      extensions:
        - parquet
        - sqlite
        - azure
        - delta
        - ducklake
        - name: delta_export
          repo: community
      attach:
        - path: "ducklake:sqlite:{{ env_var('METADATA_LOCAL_PATH', '/tmp/ducklake_metadata.db') }}"
          alias: ducklake
          options:
            data_path: "{{ env_var('ROOT_PATH') }}/Tables"
            data_inlining_row_limit: 0
